apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: avgmart-backend-hpa
  namespace: avgmart

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: avgmart-backend

  minReplicas: 1
  maxReplicas: 10

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: avgmart-frontend-hpa
  namespace: avgmart

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: avgmart-frontend

  minReplicas: 1
  maxReplicas: 10

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
