name: Build and Push Docker Images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  OWNER: suriyanandhimalai555-prog

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          sbom: false
          tags: |
            ghcr.io/${{ env.OWNER }}/avgmart-backend:latest
            ghcr.io/${{ env.OWNER }}/avgmart-backend:${{ github.sha }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          sbom: false
          build-args: |
            VITE_APP_BASE_URL=https://avgmart.com
            VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          tags: |
            ghcr.io/${{ env.OWNER }}/avgmart-frontend:latest
            ghcr.io/${{ env.OWNER }}/avgmart-frontend:${{ github.sha }}
