name: Build and Push Docker Images

on:
  push:
    branches:
      - main
permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  OWNER: suriyanandhimalai555-prog

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/avgmart-backend:latest
            ${{ env.REGISTRY }}/${{ env.OWNER }}/avgmart-backend:${{ github.sha }}
          cache-from: type=gha,scope=avgmart-backend
          cache-to: type=gha,mode=max,scope=avgmart-backend

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          platforms: linux/arm64
          push: true
          build-args: |
            VITE_APP_BASE_URL=${{ secrets.VITE_APP_BASE_URL }}
            VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/avgmart-frontend:latest
            ${{ env.REGISTRY }}/${{ env.OWNER }}/avgmart-frontend:${{ github.sha }}
          cache-from: type=gha,scope=avgmart-frontend
          cache-to: type=gha,mode=max,scope=avgmart-frontend
